In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [9]:
iris = load_iris()

In [10]:
from sklearn.model_selection import cross_val_score

In [11]:
cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target, cv=3)

array([0.98, 0.96, 0.98])

In [12]:
cross_val_score(SVC(), iris.data, iris.target, cv=3)

array([0.96, 0.98, 0.94])

In [13]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.98])